<a href="https://colab.research.google.com/github/ukeshbhaal/Guvi--Task-7-ML/blob/main/Copy_of_DataPreprocessing_Assignment-11_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Data.csv

**Step 1: Importing the libraries**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics

**Step 2: Importing dataset**

In [ ]:
data=pd.read_csv("/content/Data.csv")
print(data)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


**Step 3: Handling the missing data**

In [ ]:
data.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [ ]:
d_g=data[data['Country']=='Germany']
print(d_g)
d_g_m=d_g.mean()
m=d_g_m['Salary']
m

   Country   Age   Salary Purchased
2  Germany  30.0  54000.0        No
4  Germany  40.0      NaN       Yes
8  Germany  50.0  83000.0        No


<ipython-input-7-ab8747e75fc8>:3: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  d_g_m=d_g.mean()


68500.0

In [ ]:
data['Salary']=data.groupby([data['Country']=='Germany'])['Salary'].apply(lambda x:x.fillna(x.mean()) )

In [ ]:
data

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  68500.0       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
data['Age']=data.groupby([data['Country']=='Spain'])['Age'].apply(lambda x:x.fillna(x.mean()))

In [ ]:
data

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  68500.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  32.5  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

**Step 4: Encoding categorical data**

In [ ]:
print(data['Country'].value_counts().count())

3


In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
cols = ['Country','Purchased']
# We can also Encode labels of multiple columns at once like - cols=['Country','Purchased'] like that- but here
data[cols] = data[cols].apply(le.fit_transform)
data

Country   Age   Salary  Purchased
0        0  44.0  72000.0          0
1        2  27.0  48000.0          1
2        1  30.0  54000.0          0
3        2  38.0  61000.0          0
4        1  40.0  68500.0          1
5        0  35.0  58000.0          1
6        2  32.5  52000.0          0
7        0  48.0  79000.0          1
8        1  50.0  83000.0          0
9        0  37.0  67000.0          1

**Step 5: Creating a dummy variable**

**Step 6: Splitting the datasets into training sets and Test sets**

In [ ]:
X = data[["Country",  "Age","Salary"]].values
y = data['Purchased'].values
print(X,y)

[[0.00e+00 4.40e+01 7.20e+04]
 [2.00e+00 2.70e+01 4.80e+04]
 [1.00e+00 3.00e+01 5.40e+04]
 [2.00e+00 3.80e+01 6.10e+04]
 [1.00e+00 4.00e+01 6.85e+04]
 [0.00e+00 3.50e+01 5.80e+04]
 [2.00e+00 3.25e+01 5.20e+04]
 [0.00e+00 4.80e+01 7.90e+04]
 [1.00e+00 5.00e+01 8.30e+04]
 [0.00e+00 3.70e+01 6.70e+04]] [0 1 0 0 1 1 0 1 0 1]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=9)

**Step 7: Feature Scaling**

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
pipeline = Pipeline([   ('std_scalar', StandardScaler())])
X_train = pipeline.fit_transform(X_train)
X_test = pipeline.fit_transform(X_test)
print("\n X_train\n",X_train,"\n X_test\n",X_test)
print("\n Y_train\n",y_train,"\n Y_test\n",y_test)


 X_train
 [[ 0.         -0.92118523 -0.61767156]
 [ 1.08012345 -1.49864463 -1.3806776 ]
 [-1.08012345  0.42622003  1.0355082 ]
 [ 1.08012345  0.6187065   0.27250216]
 [-1.08012345  1.7736253   1.67134656]
 [ 1.08012345 -0.43996907 -0.8720069 ]
 [-1.08012345  0.0412471  -0.10900086]] 
 X_test
 [[ 0.70710678  0.9258201   1.00850764]
 [ 0.70710678 -1.38873015 -1.36284817]
 [-1.41421356  0.46291005  0.35434052]]

 Y_train
 [0 1 1 0 0 0 1] 
 Y_test
 [0 1 1]


In [ ]:
"""X = X
 # y = 1 * x_0 + 2 * x_1 + 3
y = y
reg = LinearRegression().fit(X, y)
print(reg.score(X, y),reg.coef_,reg.intercept_,"\nFinal\n",reg.predict(np.array([[0,44,72000]])))
"""

'X = X\n # y = 1 * x_0 + 2 * x_1 + 3\ny = y\nreg = LinearRegression().fit(X, y)\nprint(reg.score(X, y),reg.coef_,reg.intercept_,"\nFinal\n",reg.predict(np.array([[0,44,72000]])))\n'

In [ ]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X_train,y_train)
model1= LinearRegression()

In [ ]:
model1.fit(X_train,y_train)
print(model1.intercept_)
print(model1.coef_)

0.42857142857142855
[-0.29277155 -0.46199058  0.16333898]


In [ ]:
print ('Train set:\n', X_train, "\n", y_train,"\n")
print ('Test set:\n', X_test,  "\n",y_test)


Train set:
 [[ 0.         -0.92118523 -0.61767156]
 [ 1.08012345 -1.49864463 -1.3806776 ]
 [-1.08012345  0.42622003  1.0355082 ]
 [ 1.08012345  0.6187065   0.27250216]
 [-1.08012345  1.7736253   1.67134656]
 [ 1.08012345 -0.43996907 -0.8720069 ]
 [-1.08012345  0.0412471  -0.10900086]] 
 [0 1 1 0 0 0 1] 

Test set:
 [[ 0.70710678  0.9258201   1.00850764]
 [ 0.70710678 -1.38873015 -1.36284817]
 [-1.41421356  0.46291005  0.35434052]] 
 [0 1 1]


In [ ]:
score = model1.score(X_test,y_test)
print(score)
print(score * 100,"%")

0.656289540400955
65.6289540400955 %


In [ ]:
y_pred = model1.predict(X_test)
print(y_pred)
from sklearn.linear_model import LinearRegression
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

[-0.04144087  0.6405247   0.68663046]
Mean Absolute Error: 0.23809523809523814
Mean Squared Error: 0.07638010213312113
Root Mean Squared Error: 0.2763695028998698
