<a href="https://colab.research.google.com/github/ukeshbhaal/Guvi--Task-7-ML/blob/main/Copy_of_Random_Forest_Assignment16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Social_Network_Ads.csv

**Importing the libraries**

In [ ]:
import pandas as pd
import numpy as np
from sklearn import tree
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score

**Importing the dataset**

In [ ]:
data=pd.read_csv("/content/Social_Network_Ads.csv")

In [ ]:
#Encoding - Gender
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
cols = ['Gender']
# We can also Encode labels of multiple columns at once like - cols=['Gender','etc'] like that- but here
data[cols] = data[cols].apply(le.fit_transform)
data=data.drop(['User ID'], axis=1)
data

Gender  Age  EstimatedSalary  Purchased
0         1   19            19000          0
1         1   35            20000          0
2         0   26            43000          0
3         0   27            57000          0
4         1   19            76000          0
..      ...  ...              ...        ...
395       0   46            41000          1
396       1   51            23000          1
397       0   50            20000          1
398       1   36            33000          0
399       0   49            36000          1

[400 rows x 4 columns]

**Splitting the dataset into the Training set and Test set**

In [ ]:
x = data[["Gender", "Age","EstimatedSalary"]].values
y = data['Purchased'].values
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 4)

**Feature Scaling**

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
pipeline = Pipeline([   ('std_scalar', StandardScaler())])
x_train = pipeline.fit_transform(x_train)
x_test = pipeline.fit_transform(x_test)
print("\n X_train\n",x_train,"\n X_test\n",x_test)
print("\n Y_train\n",y_train,"\n Y_test\n",y_test)


 X_train
 [[ 1.00000000e+00 -1.04188331e+00 -1.46549006e+00]
 [ 1.00000000e+00 -6.63704251e-01  1.66393881e-01]
 [ 1.00000000e+00 -1.70369667e+00  4.57801728e-01]
 [-1.00000000e+00  1.98354917e+00 -8.24392800e-01]
 [-1.00000000e+00  1.41628058e+00  3.41238589e-01]
 [-1.00000000e+00  1.32173582e+00 -9.40955939e-01]
 [ 1.00000000e+00 -2.85525191e-01 -9.11815155e-01]
 [-1.00000000e+00  9.43556756e-01 -1.02837829e+00]
 [ 1.00000000e+00 -9.47338546e-01 -1.11580065e+00]
 [ 1.00000000e+00  1.98354917e+00  2.11882646e+00]
 [-1.00000000e+00  1.03810152e+00 -9.99237509e-01]
 [ 1.00000000e+00 -2.85525191e-01 -5.91266522e-01]
 [-1.00000000e+00  5.65377695e-01  2.00226332e+00]
 [ 1.00000000e+00 -1.42006237e+00 -1.46549006e+00]
 [-1.00000000e+00 -1.13642808e+00  4.98307419e-02]
 [ 1.00000000e+00  1.79445964e+00 -2.99858675e-01]
 [ 1.00000000e+00 -2.85525191e-01  4.98307419e-02]
 [-1.00000000e+00  1.22719105e+00  2.20624881e+00]
 [ 1.00000000e+00  9.43556756e-01  1.08112311e-01]
 [-1.00000000e+00 -8

**Fitting Random Forest to the Training set**

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
re=RandomForestClassifier(n_estimators=20,random_state=1)
re.fit(x_train,y_train)


RandomForestClassifier(n_estimators=20, random_state=1)

**Predicting the Test set results**

In [ ]:
y_pred=re.predict(x_test)

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 0.12
Mean Squared Error: 0.12
Root Mean Squared Error: 0.34641016151377546


**Making the Confusion Matrix**

In [ ]:
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.97      0.86      0.91        70
           1       0.74      0.93      0.82        30

    accuracy                           0.88       100
   macro avg       0.85      0.90      0.87       100
weighted avg       0.90      0.88      0.88       100

[[60 10]
 [ 2 28]]


In [ ]:
a_s=accuracy_score(y_test, y_pred)*100
a_s

88.0

**Visualising the Training set results**

In [ ]:
import matplotlib.pyplot as plt
from sklearn.tree import plot_tree

fig = plt.figure(figsize=(150, 100))
plot_tree(re.estimators_[0], 
          filled=True, impurity=True, 
          rounded=True)

In [ ]:
import graphviz
from sklearn.tree import export_graphviz

dot_data = export_graphviz(re.estimators_[-1], 
                           filled=True, impurity=True, 
                           rounded=True)

graph = graphviz.Source(dot_data, format='png')
graph

**Visualising the Test set results**